
spring.cloud.gateway.routes[0].id=microServiceConatct
spring.cloud.gateway.routes[0].uri=http://192.168.1.89:5000
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**

spring.cloud.gateway.routes[1].id=microServiceStudent
spring.cloud.gateway.routes[1].uri=http://192.168.1.89:9000
spring.cloud.gateway.routes[1].predicates[0]=Path=/examen/**

spring.cloud.gateway.routes[2].id=microServiceChat
spring.cloud.gateway.routes[2].uri=http://192.168.1.89:9095
spring.cloud.gateway.routes[2].predicates[0]=Path=/Message/**

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://127.0.0.1:8080/realms/JobBoardKeucloak/protocol/openid-connect/certs

server.port=8090

management.endpoints.web.exposure.include=*

